public with sharing class OpportunityTriggerHandler {
    public  static void beforeInsert() {
        
    }
    public  static void afterInsert() {
        
    } 
    public  static void beforeUpdate() {
        
    }
    public  static void afterUpdate() {
        
    }
    public  static void beforeDelete() {
        
    }
    public  static void afterDelete() {
        
    }
    public  static void afterUnDelete() {
        
    }
}